// Demo data for HealthVerse AI
export const demoUsers = {
  patient: {
    id: "1",
    name: "Sarah Chen",
    email: "patient@demo.com",
    role: "patient",
    avatar: "/asian-woman-smiling.png",
    age: 34,
    condition: "Post-surgical recovery",
    joinedDate: "2024-01-15",
    preferredLanguage: "en",
    healingTheme: "calm",
    emergencyContact: "Michael Chen",
    medicalId: "HC-2024-001",
  },
  family: {
    id: "2",
    name: "Michael Chen",
    email: "family@demo.com",
    role: "family",
    avatar: "/asian-man-caring.png",
    relationship: "Spouse",
    patientId: "1",
    notifications: true,
    emergencyAccess: true,
  },
  doctor: {
    id: "3",
    name: "Dr. Rodriguez",
    email: "doctor@demo.com",
    role: "doctor",
    avatar: "/hispanic-doctor-professional.png",
    specialty: "Orthopedic Surgery",
    patients: ["1"],
    license: "MD-12345",
    hospital: "HealthVerse Medical Center",
  },
}

export const demoHealthData = [
  {
    date: "2024-01-20",
    moodScore: 7,
    heartRate: 72,
    sleepHours: 7.5,
    healingScore: 78,
    activities: ["meditation", "light_walk", "breathing_exercise"],
    painLevel: 3,
    energyLevel: 7,
    stressLevel: 4,
  },
  {
    date: "2024-01-19",
    moodScore: 6,
    heartRate: 75,
    sleepHours: 6.8,
    healingScore: 75,
    activities: ["meditation", "stretching"],
    painLevel: 4,
    energyLevel: 6,
    stressLevel: 5,
  },
  {
    date: "2024-01-18",
    moodScore: 8,
    heartRate: 68,
    sleepHours: 8.2,
    healingScore: 82,
    activities: ["meditation", "light_walk", "music_therapy", "family_call"],
    painLevel: 2,
    energyLevel: 8,
    stressLevel: 3,
  },
  {
    date: "2024-01-17",
    moodScore: 5,
    heartRate: 78,
    sleepHours: 6.2,
    healingScore: 68,
    activities: ["breathing_exercise"],
    painLevel: 5,
    energyLevel: 5,
    stressLevel: 6,
  },
  {
    date: "2024-01-16",
    moodScore: 7,
    heartRate: 70,
    sleepHours: 7.8,
    healingScore: 76,
    activities: ["meditation", "stretching", "music_therapy"],
    painLevel: 3,
    energyLevel: 7,
    stressLevel: 4,
  },
  {
    date: "2024-01-15",
    moodScore: 6,
    heartRate: 74,
    sleepHours: 7.0,
    healingScore: 70,
    activities: ["meditation", "family_call"],
    painLevel: 4,
    energyLevel: 6,
    stressLevel: 5,
  },
  {
    date: "2024-01-14",
    moodScore: 8,
    heartRate: 69,
    sleepHours: 8.5,
    healingScore: 80,
    activities: ["meditation", "vr_session", "music_therapy"],
    painLevel: 2,
    energyLevel: 8,
    stressLevel: 3,
  },
]

export const demoRecoveryPlan = [
  {
    id: "1",
    title: "Morning Meditation",
    description: "Start your day with 10 minutes of guided breathing",
    completed: true,
    type: "meditation",
    duration: "10 min",
  },
  {
    id: "2",
    title: "Gentle Stretching",
    description: "Light stretching exercises for mobility",
    completed: true,
    type: "exercise",
    duration: "15 min",
  },
  {
    id: "3",
    title: "Medication Reminder",
    description: "Take prescribed pain medication with food",
    completed: false,
    type: "medication",
    duration: "2 min",
  },
  {
    id: "4",
    title: "VR Forest Walk",
    description: "Immersive nature experience for stress relief",
    completed: false,
    type: "vr",
    duration: "20 min",
  },
  {
    id: "5",
    title: "Family Check-in",
    description: "Connect with loved ones for emotional support",
    completed: false,
    type: "social",
    duration: "15 min",
  },
]

export const demoAchievements = [
  {
    id: "1",
    badge: "First Steps",
    description: "Completed your first day of recovery",
    earnedAt: "2024-01-15",
    icon: "👣",
    color: "from-teal-500 to-teal-600",
  },
  {
    id: "2",
    badge: "Meditation Master",
    description: "7 days of consistent meditation",
    earnedAt: "2024-01-18",
    icon: "🧘‍♀️",
    color: "from-purple-500 to-purple-600",
  },
  {
    id: "3",
    badge: "Family Bond",
    description: "Connected with family 5 times this week",
    earnedAt: "2024-01-19",
    icon: "👨‍👩‍👧‍👦",
    color: "from-coral-500 to-coral-600",
  },
  {
    id: "4",
    badge: "VR Explorer",
    description: "Visited all 3 healing environments",
    earnedAt: "2024-01-20",
    icon: "🌲",
    color: "from-green-500 to-green-600",
  },
  {
    id: "5",
    badge: "Healing Streak",
    description: "5 days of consistent progress",
    earnedAt: "2024-01-20",
    icon: "⚡",
    color: "from-yellow-500 to-yellow-600",
  },
]

export const demoFamilyMessages = [
  {
    id: "1",
    fromUserId: "2",
    fromName: "Michael",
    message: "How are you feeling today? Remember to take your medication!",
    type: "text",
    createdAt: "2024-01-20T09:30:00Z",
    avatar: "/asian-man-caring.png",
  },
  {
    id: "2",
    fromUserId: "4",
    fromName: "Mom",
    message: "Sending you love and healing energy. You're doing amazing! 💕",
    type: "text",
    createdAt: "2024-01-20T08:15:00Z",
    avatar: "/older-asian-woman-smiling.png",
  },
  {
    id: "3",
    fromUserId: "2",
    fromName: "Michael",
    message: "I made your favorite soup! Can't wait to bring it over later.",
    type: "text",
    createdAt: "2024-01-19T18:45:00Z",
    avatar: "/asian-man-caring.png",
  },
]

export const demoAIResponses = [
  {
    trigger: "how are you feeling",
    response:
      "I can sense you're looking for some comfort today. Your recent vitals show you're making steady progress! Would you like to try a breathing exercise or perhaps visit the Forest Sanctuary in VR?",
    mood: "supportive",
  },
  {
    trigger: "pain",
    response:
      "I understand you're experiencing discomfort. Let's work through this together. I recommend trying the guided meditation for pain relief, and I'll notify your care team about your current pain levels.",
    mood: "caring",
  },
  {
    trigger: "anxious",
    response:
      "Anxiety is completely normal during recovery. Your breathing pattern suggests some stress - let's try the 4-7-8 breathing technique together. I'm here with you every step of the way.",
    mood: "calming",
  },
  {
    trigger: "family",
    response:
      "Your family's support is incredible! Michael sent you a message this morning, and your healing score has improved 15% since you started connecting with loved ones regularly.",
    mood: "encouraging",
  },
  {
    trigger: "progress",
    response:
      "You're doing wonderfully! Your healing score has increased from 68 to 78 this week. Your consistency with meditation and gentle movement is really paying off. Keep it up!",
    mood: "celebratory",
  },
]

export const demoHealingRooms = [
  {
    id: "forest",
    name: "Forest Sanctuary",
    description: "Peaceful woodland with gentle streams and bird songs",
    image: "/peaceful-forest-sunlight.png",
    benefits: ["Stress Relief", "Nature Connection", "Calm Focus"],
    duration: "10-30 min",
    popularity: 95,
    sessions: 1247,
    avgRating: 4.8,
    therapeuticFocus: "Anxiety & Stress Relief",
  },
  {
    id: "beach",
    name: "Healing Beach",
    description: "Tranquil ocean waves with warm sand and sunset",
    image: "/peaceful-beach-sunset.png",
    benefits: ["Deep Relaxation", "Emotional Release", "Inner Peace"],
    duration: "15-45 min",
    popularity: 88,
    sessions: 892,
    avgRating: 4.7,
    therapeuticFocus: "Depression & Mood Enhancement",
  },
  {
    id: "temple",
    name: "Sacred Temple",
    description: "Serene meditation space with soft chanting and incense",
    image: "/peaceful-temple-meditation.png",
    benefits: ["Spiritual Healing", "Mindfulness", "Pain Relief"],
    duration: "20-60 min",
    popularity: 92,
    sessions: 1056,
    avgRating: 4.9,
    therapeuticFocus: "Pain Management & Mindfulness",
  },
]

export const demoNotifications = [
  {
    id: "1",
    type: "achievement",
    title: "New Achievement Unlocked!",
    message: "You earned the 'Healing Streak' badge for 5 consecutive days of progress.",
    timestamp: "2024-01-20T10:30:00Z",
    read: false,
    priority: "medium",
  },
  {
    id: "2",
    type: "family",
    title: "Family Message",
    message: "Michael sent you a supportive message with a photo.",
    timestamp: "2024-01-20T09:15:00Z",
    read: false,
    priority: "low",
  },
  {
    id: "3",
    type: "health",
    title: "Mood Check-in",
    message: "How are you feeling today? SwasthAI is here to help.",
    timestamp: "2024-01-20T08:00:00Z",
    read: true,
    priority: "medium",
  },
  {
    id: "4",
    type: "appointment",
    title: "Upcoming Appointment",
    message: "Reminder: Follow-up with Dr. Rodriguez on Jan 25, 2024.",
    timestamp: "2024-01-19T16:00:00Z",
    read: true,
    priority: "high",
  },
]

export const demoAnalytics = {
  weeklyProgress: {
    healingScore: { current: 78, previous: 73, change: +5 },
    moodScore: { current: 7.2, previous: 6.8, change: +0.4 },
    sleepQuality: { current: 7.5, previous: 7.1, change: +0.4 },
    activityLevel: { current: 85, previous: 78, change: +7 },
  },
  monthlyTrends: {
    totalSessions: 42,
    vrHours: 18.5,
    familyInteractions: 23,
    achievementsEarned: 5,
    complianceRate: 87,
  },
  insights: [
    {
      category: "mood",
      insight: "Your mood scores are 25% higher on days when you connect with family.",
      recommendation: "Continue daily family check-ins for optimal emotional support.",
    },
    {
      category: "sleep",
      insight: "VR sessions before bedtime improve your sleep quality by 30%.",
      recommendation: "Try the Temple environment 1 hour before sleep.",
    },
    {
      category: "recovery",
      insight: "Your healing score accelerates with consistent meditation practice.",
      recommendation: "Maintain your current 15-minute daily meditation routine.",
    },
  ],
}

export const demoMealPlans = [
  {
    id: "1",
    name: "Anti-Inflammatory Recovery Plan",
    description: "Nutrient-rich meals to support healing and reduce inflammation",
    duration: "7 days",
    calories: 1800,
    meals: [
      {
        id: "breakfast-1",
        name: "Golden Turmeric Smoothie Bowl",
        type: "breakfast",
        calories: 420,
        protein: 15,
        carbs: 65,
        fat: 12,
        ingredients: ["Banana", "Turmeric", "Coconut milk", "Chia seeds", "Berries"],
        image: "/golden-milk-turmeric-drink.png",
        prepTime: "10 min",
        benefits: ["Anti-inflammatory", "Antioxidant-rich", "Digestive support"],
      },
      {
        id: "lunch-1",
        name: "Mediterranean Quinoa Salad",
        type: "lunch",
        calories: 520,
        protein: 18,
        carbs: 58,
        fat: 22,
        ingredients: ["Quinoa", "Chickpeas", "Cucumber", "Tomatoes", "Olive oil", "Feta cheese"],
        image: "/mediterranean-quinoa-salad.png",
        prepTime: "15 min",
        benefits: ["Heart-healthy", "High fiber", "Complete protein"],
      },
      {
        id: "dinner-1",
        name: "Healing Bone Broth Soup",
        type: "dinner",
        calories: 380,
        protein: 25,
        carbs: 35,
        fat: 15,
        ingredients: ["Bone broth", "Vegetables", "Ginger", "Garlic", "Herbs"],
        image: "/healing-bone-broth.png",
        prepTime: "25 min",
        benefits: ["Collagen support", "Immune boosting", "Easy digestion"],
      },
    ],
    nutritionGoals: {
      protein: "25%",
      carbs: "45%",
      fat: "30%",
      fiber: "35g",
      water: "2.5L",
    },
  },
]

export const demoCommunityPosts = [
  {
    id: "1",
    author: {
      name: "Emma Rodriguez",
      avatar: "/young-hispanic-woman.png",
      role: "patient",
      joinedDate: "2023-12-01",
    },
    title: "My VR Healing Journey - 30 Days Later",
    content:
      "I wanted to share my experience with the VR healing rooms. When I started, I was skeptical about virtual reality helping with my anxiety and chronic pain. But after 30 days of regular sessions in the Forest Sanctuary, I've seen remarkable improvements...",
    category: "Success Stories",
    tags: ["VR Therapy", "Anxiety", "Chronic Pain", "Recovery"],
    likes: 47,
    comments: 12,
    createdAt: "2024-01-19T14:30:00Z",
    featured: true,
  },
  {
    id: "2",
    author: {
      name: "David Kim",
      avatar: "/middle-aged-man-contemplative.png",
      role: "patient",
      joinedDate: "2024-01-10",
    },
    title: "Tips for Family Communication During Recovery",
    content:
      "Recovery can be isolating, but I've found that regular communication with family through HealthVerse has made a huge difference. Here are some strategies that worked for me...",
    category: "Tips & Advice",
    tags: ["Family Support", "Communication", "Mental Health"],
    likes: 23,
    comments: 8,
    createdAt: "2024-01-18T10:15:00Z",
    featured: false,
  },
  {
    id: "3",
    author: {
      name: "Dr. Sarah Mitchell",
      avatar: "/hispanic-doctor-professional.png",
      role: "healthcare_provider",
      joinedDate: "2023-11-15",
    },
    title: "The Science Behind VR Therapy in Healthcare",
    content:
      "As a healthcare provider, I've been amazed by the clinical results we're seeing with VR therapy integration. Let me share some insights about how virtual reality affects the brain during healing...",
    category: "Expert Insights",
    tags: ["VR Therapy", "Medical Research", "Healthcare Innovation"],
    likes: 89,
    comments: 24,
    createdAt: "2024-01-17T16:45:00Z",
    featured: true,
  },
]

export const demoFitnessData = {
  weeklyStats: {
    totalWorkouts: 5,
    totalMinutes: 127,
    caloriesBurned: 890,
    averageHeartRate: 118,
    strengthGains: 15,
    flexibilityScore: 78,
  },
  workoutHistory: [
    {
      id: "1",
      date: "2024-01-20",
      type: "Gentle Recovery",
      duration: 18,
      exercises: ["Neck rolls", "Shoulder shrugs", "Arm circles", "Deep breathing"],
      caloriesBurned: 85,
      avgHeartRate: 95,
      completed: true,
      rating: 4,
    },
    {
      id: "2",
      date: "2024-01-19",
      type: "Strength Building",
      duration: 25,
      exercises: ["Modified push-ups", "Bodyweight squats", "Resistance bands", "Core work"],
      caloriesBurned: 180,
      avgHeartRate: 125,
      completed: true,
      rating: 5,
    },
    {
      id: "3",
      date: "2024-01-18",
      type: "Cardio Boost",
      duration: 22,
      exercises: ["Brisk walking", "Light jogging", "Dancing", "Cool down"],
      caloriesBurned: 220,
      avgHeartRate: 135,
      completed: true,
      rating: 4,
    },
  ],
  personalRecords: {
    longestWorkout: 45,
    mostCaloriesBurned: 320,
    bestConsistencyStreak: 12,
    strengthImprovement: 25,
  },
}

export const demoGamificationData = {
  currentLevel: 8,
  totalPoints: 2450,
  pointsToNextLevel: 550,
  dailyQuests: [
    {
      id: "1",
      title: "Morning Meditation",
      description: "Complete 10 minutes of meditation",
      points: 50,
      completed: true,
      category: "wellness",
    },
    {
      id: "2",
      title: "Family Connection",
      description: "Send a message to a family member",
      points: 30,
      completed: true,
      category: "social",
    },
    {
      id: "3",
      title: "VR Session",
      description: "Spend 15 minutes in a healing room",
      points: 75,
      completed: false,
      category: "therapy",
    },
    {
      id: "4",
      title: "Fitness Challenge",
      description: "Complete a 20-minute workout",
      points: 100,
      completed: false,
      category: "fitness",
    },
  ],
  weeklyChallenge: {
    title: "Mindful Week",
    description: "Complete meditation sessions for 7 consecutive days",
    progress: 5,
    target: 7,
    reward: 500,
    daysRemaining: 2,
  },
  leaderboard: [
    { rank: 1, name: "Alex Chen", points: 3200, avatar: "/asian-woman-smiling.png" },
    { rank: 2, name: "Maria Santos", points: 2890, avatar: "/young-hispanic-woman.png" },
    { rank: 3, name: "You (Sarah)", points: 2450, avatar: "/asian-woman-smiling.png" },
    { rank: 4, name: "David Kim", points: 2380, avatar: "/middle-aged-man-contemplative.png" },
    { rank: 5, name: "Emma Rodriguez", points: 2150, avatar: "/young-hispanic-woman.png" },
  ],
}

export const demoLearningContent = {
  courses: [
    {
      id: "1",
      title: "Understanding Your Recovery Journey",
      description: "A comprehensive guide to the healing process",
      duration: "45 min",
      modules: 6,
      progress: 83,
      category: "Recovery Basics",
      difficulty: "Beginner",
      rating: 4.8,
      enrolled: 1247,
    },
    {
      id: "2",
      title: "Mindfulness for Pain Management",
      description: "Learn evidence-based techniques for managing chronic pain",
      duration: "60 min",
      modules: 8,
      progress: 25,
      category: "Pain Management",
      difficulty: "Intermediate",
      rating: 4.9,
      enrolled: 892,
    },
    {
      id: "3",
      title: "Nutrition for Healing",
      description: "Discover foods that support recovery and reduce inflammation",
      duration: "35 min",
      modules: 5,
      progress: 0,
      category: "Nutrition",
      difficulty: "Beginner",
      rating: 4.7,
      enrolled: 1456,
    },
  ],
  quickReads: [
    {
      id: "1",
      title: "5 Breathing Techniques for Instant Calm",
      readTime: "3 min",
      category: "Stress Management",
      featured: true,
    },
    {
      id: "2",
      title: "The Science of Sleep and Recovery",
      readTime: "5 min",
      category: "Sleep Health",
      featured: false,
    },
    {
      id: "3",
      title: "Building Resilience Through Gratitude",
      readTime: "4 min",
      category: "Mental Health",
      featured: true,
    },
  ],
  emergencyGuides: [
    {
      id: "1",
      title: "Managing Panic Attacks",
      steps: 6,
      category: "Mental Health Emergency",
    },
    {
      id: "2",
      title: "Pain Crisis Management",
      steps: 8,
      category: "Physical Health Emergency",
    },
    {
      id: "3",
      title: "When to Seek Immediate Help",
      steps: 4,
      category: "General Emergency",
    },
  ],
}

export const demoProviderData = {
  patientOverview: {
    totalPatients: 24,
    activeToday: 18,
    needsAttention: 3,
    improvingTrend: 15,
    averageHealingScore: 76,
  },
  recentAlerts: [
    {
      id: "1",
      patientName: "Sarah Chen",
      type: "mood_drop",
      severity: "medium",
      message: "Mood score dropped to 4/10, down from 7/10 yesterday",
      timestamp: "2024-01-20T09:15:00Z",
      acknowledged: false,
    },
    {
      id: "2",
      patientName: "David Kim",
      type: "missed_medication",
      severity: "high",
      message: "Missed medication reminder for 2 consecutive days",
      timestamp: "2024-01-20T08:30:00Z",
      acknowledged: true,
    },
  ],
  upcomingAppointments: [
    {
      id: "1",
      patientName: "Sarah Chen",
      type: "Follow-up",
      date: "2024-01-25T10:00:00Z",
      duration: 30,
      notes: "Post-surgical recovery check",
    },
    {
      id: "2",
      patientName: "Emma Rodriguez",
      type: "Initial Consultation",
      date: "2024-01-25T14:30:00Z",
      duration: 60,
      notes: "Chronic pain management",
    },
  ],
}
